// C++ standard library includes
#include <algorithm>
#include <chrono>
#include <numeric>
#include <stdexcept>

// OpenCV includes
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

// Google Test includes
#include <gtest/gtest.h>

// Local includes
#define private public
#include "rf_detr_trt_backend/rf_detr_trt_backend.hpp"
#undef private

#include "rf_detr_trt_backend/detection_utils.hpp"


class RFDetrTrtBackendTest : public ::testing::Test
{
protected:
  void SetUp() override
  {
    // Configure the inferencer. No engine-specific overrides needed until
    // a fine-tuned KITTI checkpoint changes normalization stats.
    rf_detr_trt_backend::RFDetrTrtBackend::Config conf;
    conf.warmup_iterations = 2;
    conf.log_level = rf_detr_trt_backend::LogLevel::kInfo;

    try {
      detector = std::make_unique<rf_detr_trt_backend::RFDetrTrtBackend>(engine_path_, conf);
    } catch (const std::exception & e) {
      GTEST_SKIP() << "Failed to initialize TensorRT inferencer: " << e.what();
    }

    // Read back the engine-resolved geometry now that construction has
    // succeeded.
    // INTO Config; now they're read back FROM the loaded engine, so this
    // test can no longer silently drift out of sync with whatever
    // engine_path_ actually points to.
    input_size_ = detector->input_height();  // == input_width() - square-only, enforced at construction
    num_queries_ = detector->num_queries();
    num_classes_ = detector->num_classes();
  }

  void TearDown() override
  {
  }

  // A loaded test image plus its letterboxed square form and the
  // LetterboxInfo needed to map detections back. Bundling all three
  // together is what lets every test below do the full round trip
  // (letterbox -> infer -> unletterbox) instead of only exercising the
  // square-input half of the pipeline. No forced resize here - `original`
  // stays exactly whatever the test image file actually is; its dimensions
  // are read back from info.orig_width/orig_height (which letterbox_square()
  // already computes from image.cols/rows), not duplicated as constants.
  struct TestImage
  {
    cv::Mat original;   // whatever size the file on disk actually is
    cv::Mat padded;     // letterboxed square: input_size_ x input_size_
    rf_detr_trt_backend::utils::LetterboxInfo info;
  };

  TestImage load_test_image(const std::string & path)
  {
    TestImage img;
    img.original = cv::imread(path);
    if (img.original.empty()) {
      throw std::runtime_error("Failed to load test image: " + path);
    }

    img.padded = rf_detr_trt_backend::utils::letterbox_square(
      img.original, input_size_, &img.info);

    return img;
  }

  void expect_well_formed(
    const rf_detr_trt_backend::Detections & detections, int width, int height)
  {
    for (const auto & d : detections) {
      EXPECT_GE(d.box.x1, 0.0f);
      EXPECT_GE(d.box.y1, 0.0f);
      EXPECT_LE(d.box.x2, static_cast<float>(width));
      EXPECT_LE(d.box.y2, static_cast<float>(height));
      EXPECT_LT(d.box.x1, d.box.x2);
      EXPECT_LT(d.box.y1, d.box.y2);
      EXPECT_GE(d.class_id, 0);
      EXPECT_LT(d.class_id, num_classes_);
      EXPECT_GE(d.score, 0.0f);
      EXPECT_LE(d.score, 1.0f);
    }
  }

  std::unique_ptr<rf_detr_trt_backend::RFDetrTrtBackend> detector;

  // protected, not private: TEST_F(...) bodies are subclasses of this
  // fixture and reference image_path_ directly - private members aren't
  // accessible from a derived class, even one generated by a gtest macro.
  const std::string image_path_ = "image_000.png";

public:
  int input_size_ = 0;
  int num_queries_ = 0;
  int num_classes_ = 0;

private:
  // engine_path_ stays private: only ever used inside SetUp(), a member of
  // this class itself, so private access is fine here.
  const std::string engine_path_ = "rf_detr_large_704x704.engine";
};

// Full round trip: whatever shape image_000.png actually is -> letterbox_square()
// -> infer() -> unletterbox_detections() -> output written back at that
// SAME original shape, not the model's square input shape.
TEST_F(RFDetrTrtBackendTest, TestBasicInference)
{
  TestImage img = load_test_image(image_path_);
  EXPECT_EQ(img.padded.cols, input_size_);
  EXPECT_EQ(img.padded.rows, input_size_);
  EXPECT_EQ(img.padded.type(), CV_8UC3);

  auto start = std::chrono::high_resolution_clock::now();
  rf_detr_trt_backend::Detections detections_padded = detector->infer(img.padded);
  auto end = std::chrono::high_resolution_clock::now();

  auto duration = std::chrono::duration<double, std::milli>(end - start);
  std::cout << "GPU infer with decode: " << duration.count() << " ms" << std::endl;
  std::cout << "Detections: " << detections_padded.size() << std::endl;

  expect_well_formed(detections_padded, input_size_, input_size_);

  auto detections_original =
    rf_detr_trt_backend::utils::unletterbox_detections(detections_padded, img.info);
  EXPECT_LE(detections_original.size(), detections_padded.size());
  expect_well_formed(detections_original, img.info.orig_width, img.info.orig_height);

  cv::Mat overlay = rf_detr_trt_backend::utils::draw_detections(
    img.original, detections_original);
  EXPECT_EQ(overlay.size(), img.original.size());  // original file's own size, not input_size_ x input_size_
  EXPECT_EQ(overlay.type(), CV_8UC3);

  cv::imwrite("test_output_detections.png", overlay);
}

// Directly exercises infer()'s hard-require-exact-size contract: a
// non-square, non-engine-sized image must throw rather than be silently
// resized (see RFDetrTrtBackend::infer()'s doc comment).
TEST_F(RFDetrTrtBackendTest, TestThrowsOnWrongSize)
{
  cv::Mat wrong_size(input_size_ / 2, input_size_, CV_8UC3, cv::Scalar(0, 0, 0));
  EXPECT_THROW(detector->infer(wrong_size), std::invalid_argument);
}

// Directly exercises infer()'s continuity requirement: a non-contiguous ROI
// view must throw rather than silently reading past/around the view.
TEST_F(RFDetrTrtBackendTest, TestThrowsOnNonContinuousImage)
{
  cv::Mat full(input_size_, input_size_ * 2, CV_8UC3, cv::Scalar(0, 0, 0));
  cv::Mat roi = full(cv::Rect(0, 0, input_size_, input_size_));  // non-contiguous view
  ASSERT_FALSE(roi.isContinuous());
  EXPECT_THROW(detector->infer(roi), std::invalid_argument);
}

// Pure infer() latency loop. Uses the same letterboxed test image as the
// other tests for consistency, but deliberately does NOT call
// unletterbox_detections() inside the timed loop - that's CPU work
// unrelated to GPU inference and would skew the very thing being measured.
TEST_F(RFDetrTrtBackendTest, TestMultipleInferences)
{
  TestImage img = load_test_image(image_path_);

  const int num_iterations = 10;
  std::vector<double> inference_times;

  for (int i = 0; i < num_iterations; ++i) {
    auto start = std::chrono::high_resolution_clock::now();
    auto detections = detector->infer(img.padded);
    auto end = std::chrono::high_resolution_clock::now();

    auto duration = std::chrono::duration<double, std::milli>(end - start);
    inference_times.push_back(duration.count());

    expect_well_formed(detections, input_size_, input_size_);
  }

  double avg_time = std::accumulate(inference_times.begin(), inference_times.end(), 0.0) /
    inference_times.size();
  double min_time = *std::min_element(inference_times.begin(), inference_times.end());
  double max_time = *std::max_element(inference_times.begin(), inference_times.end());

  std::cout << "Multiple inference statistics:" << std::endl;
  std::cout << "  Average: " << avg_time << " ms" << std::endl;
  std::cout << "  Min: " << min_time << " ms" << std::endl;
  std::cout << "  Max: " << max_time << " ms" << std::endl;

  // Performance expectation (adjust based on your hardware)
  EXPECT_LT(avg_time, 100.0);
}

// Pure infer() latency benchmark - same rationale as TestMultipleInferences
// for not including unletterbox_detections() in the timed section.
TEST_F(RFDetrTrtBackendTest, TestBenchmarkInference)
{
  TestImage img = load_test_image(image_path_);

  const int warmup_iterations = 10;
  const int benchmark_iterations = 100;

  for (int i = 0; i < warmup_iterations; ++i) {
    detector->infer(img.padded);
  }

  auto start = std::chrono::high_resolution_clock::now();

  for (int i = 0; i < benchmark_iterations; ++i) {
    detector->infer(img.padded);
  }

  auto end = std::chrono::high_resolution_clock::now();
  auto total_duration = std::chrono::duration<double, std::milli>(end - start);

  double avg_time = total_duration.count() / benchmark_iterations;
  double fps = 1000.0 / avg_time;

  std::cout << "Benchmark Results:" << std::endl;
  std::cout << "Iterations: " << benchmark_iterations << std::endl;
  std::cout << "Total time: " << total_duration.count() << " ms" << std::endl;
  std::cout << "Average time per inference: " << avg_time << " ms" << std::endl;
  std::cout << "Throughput: " << fps << " FPS" << std::endl;
}

// Full round trip across all available test images, each written out at
// its own original shape (not the model's square input shape).
TEST_F(RFDetrTrtBackendTest, TestMultipleImages)
{
  std::vector<std::string> test_images = {
    "image_000.png",
    "image_001.png",
    "image_002.png"
  };

  int successful_tests = 0;

  for (const auto & path : test_images) {
    cv::Mat probe = cv::imread(path);
    if (probe.empty()) {
      std::cout << "Skipping missing image: " << path << std::endl;
      continue;
    }

    try {
      TestImage img = load_test_image(path);

      auto detections_padded = detector->infer(img.padded);
      expect_well_formed(detections_padded, input_size_, input_size_);

      auto detections_original = rf_detr_trt_backend::utils::unletterbox_detections(
        detections_padded, img.info);
      expect_well_formed(detections_original, img.info.orig_width, img.info.orig_height);

      auto overlay = rf_detr_trt_backend::utils::draw_detections(
        img.original, detections_original);
      cv::imwrite("test_output_detections_" + std::to_string(successful_tests) + ".png", overlay);

      successful_tests++;
    } catch (const std::exception & e) {
      FAIL() << "Failed to process image " << path << ": " << e.what();
    }
  }

  EXPECT_GT(successful_tests, 0) << "No test images were successfully processed";
  std::cout << "Successfully processed " << successful_tests << " test images" << std::endl;
}
